### ISSUE TITLE
Include Aleph Alpha

### ISSUE THREAD

**Issue by peterschmidt85** [johko/awesome-german-open-source-ml#2]
https://huggingface.co/Aleph-Alpha

**Comment by johko** [comment]
Hey, I think we already discussed this on LinkedIn but just to not leave this issue dangling around:
Releasing the weights for one model (in various forms) as such a big and hyped company as Aleph Alpha, I would refrain from already calling them an open-source-focused company.
I'd be happy if they are focusing more on open-source now and begin to release more and when that happens, I'm happy to include them here.
