### ISSUE TITLE
Include Trafilatura

### ISSUE THREAD

**Issue by adbar** [johko/awesome-german-open-source-ml#4]
Hi, I'd like to include [Trafilatura](https://github.com/adbar/trafilatura) but I'm not sure where.

May I suggest an additional category like "training data" or "data collection and preprocessing"?

**Comment by johko** [comment]
Hey, sorry for the late response. And yes, Trafilatura looks fitting. I think as we also have dlt/dltHub on the list, we could have a "Data Collection and Preprocessing" section as you suggested. Would you like to create a PR for that @adbar?

**Comment by adbar** [comment]
@johko Done :+1:
